export const API_ENDPOINT = 'https://www.thecocktaildb.com/api/json/v1/1/';
export const API_ENDPOINT_2 = 'https://www.thecocktaildb.com/api/json/v2/1/';

export const CATEGORY = [
  'absolut',
  'ale',
  'brandy',
  'whiskey',
  'rum',
  'bourbon',
  'applejack',
  'champagne',
  'cognac',
  'liqueur',
  'cassis',
  'dubonnet',
  'vermouth',
  'firewater',
  'gin',
  'johnnie walker',
  'kahlua',
  'lager',
  'vodka',
  'ouzo',
  'schnapps',
  'pisco',
  'scotch',
  'sherry',
  'southern comfort',
  'tequila',
  'triple sec',
  'ricard',
  'sambuca',
  'wine',
  'galliano',
  'everclear',
  'port',
  'amaretto',
  'bitters',
];
